### ISSUE TITLE
Jetson.GPIO on Connect Tech astro carrier

### ISSUE THREAD

**Issue by FSUSE** [NVIDIA/jetson-gpio#45]
Hello, 

I am currently using this library. I am using the Astro carrier board from connect Tech. Is there a way to run this library on the Astro?

I get the following message:
![Screenshot from 2020-10-01 20-19-12](https://user-images.githubusercontent.com/72223755/94847851-6cc2bc00-0423-11eb-89e8-7304692ac4de.png)

Thank you

**Comment by swarren** [comment]
For third-party boards, it's up to the vendor to implement support in Jetson.GPIO if they wish.

However, it doesn't look like there's any 40-pin GPIO expansion connector on the Astro board, so it may not make sense to support this board. The intent of Jetson.GPIO is to provide compatibility for software written to access a Raspberry Pi's 40-pin GPIO expansion connector. At the very least, if support for Astro was added to Jetson.GPIO, the pin numbering wouldn't be compatible with any existing software.

Can you describe your use-case a bit, e.g.:
* Are you writing new software or are you porting something existing?
* Do you care about compatibility of pin numbers with existing software or other board, or not?
* Do you explicitly want to use the Jetson.GPIO API, or did you try it simply because it was available. Perhaps an alternative API or mechanism would be suitable if it existed?

Thanks.

**Comment by FSUSE** [comment]
Hi swarren, 

thank you for your reply
I want to write a software to control the GPIOs of Astro or Jetson. 
I can control the GPIO pins via the terminal. 

The program is implemented in an image processing software. 

Therefore I wanted to use this library.

**Comment by swarren** [comment]
OK, you'll need to talk to Connect Tech re: having them add support to the library for the Astro board.

I guess they can invent a different pin naming scheme for this board, since it doesn't have a 40-pin header, and I guess leave some of the pin lookup table columns blank (e.g. the BCM mode values won't make any sense).
