### ISSUE TITLE
Edge detection: how to know which edge triggered 

### ISSUE THREAD

**Issue by danaki** [NVIDIA/jetson-gpio#47]
Hello, I'm trying to measure the input pwm duty cycle (see #7).

```
import RPi.GPIO as GPIO
import time

but_pin = 23  # Board pin 18

t = time.time()
def callback_one(channel):
    global t

    print(GPIO.input(channel), (time.time() - t) * 100000)
    t = time.time()

def main():
    GPIO.setmode(GPIO.BOARD)  # BOARD pin-numbering scheme
    GPIO.setup(but_pin, GPIO.IN)  # button pin set as input

    GPIO.add_event_detect(but_pin, GPIO.BOTH)
    GPIO.add_event_callback(but_pin, callback_one)

    try:
        while True:
            pass
```

Example output looks like:
```
1 2555.6087493896484
0 2555.561065673828
0 2562.1652603149414
0 2051.234245300293
0 2558.2313537597656
0 2553.6537170410156
0 547.2898483276367
0 1540.8754348754883
0 2555.537223815918
1 1574.6116638183594
0 558.7100982666016
0 13.73291015625
1 1337.4090194702148
0 1032.3286056518555
0 523.2572555541992
0 1030.6119918823242
1 519.4664001464844
```

Since because API doesn't allow to handle each type of edge FALLING, RISING separately, the only method to know what level was switched is using `GPIO.input(channel)`, but as you can notice it doesn't work well (first column of the output). Possibly because level is not yet switched at the moment when edge is triggered. I'm 100% sure that's the PWM in the input, I checked it using signal analyzer so that output must be 0, 1, 0, 1, 0... etc. Can you please update the API and provide an optional argument to callback function specifying what type of edge has triggered the event?

**Comment by swarren** [comment]
The Jetson.GPIO API is fixed, since Jetson.GPIO is intended to be a straight re-implementation of RPi.GPIO. Equally, the current implementation of Jetson.GPIO uses the Linux kernel sysfs GPIO API, which doesn't provide edge information.

There are a few of ways you might approach this:

1) Simply poll the GPIO input value as rapidly as possible. For example, see the code at https://github.com/NVIDIA/jetson-gpio/blob/master/samples/test_all_apis.py#L641

2) Write code that uses the Linux kernel's GPIO character device. This does provide rising-vs-falling information in the GPIO event data. See:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/gpio.h#n450

3) Write a Linux kernel driver, which uses the Linux kernel's own internal GPIO API.
