### ISSUE TITLE
Jetson Nano developer kit (4GB) not detected correctly

### ISSUE THREAD

**Issue by rosterloh** [NVIDIA/jetson-gpio#48]
```
$ ls -l /proc/device-tree/chosen/plugin-manager/ids
total 0
-r--r--r-- 1 root root 26 Jan 29 10:21 3448-0000-400
drwxr-xr-x 3 root root  0 Jan 29 10:21 connection
-r--r--r-- 1 root root  4 Jan 29 10:21 name
```

Library reports:
```
WARNING: Carrier board is not from a Jetson Developer Kit.
WARNNIG: Jetson.GPIO library has not been verified with this carrier board,
WARNING: and in fact is unlikely to work correctly.
```

**Comment by swarren** [comment]
This issue occurs outside Jetson.GPIO, rather than being a problem in Jetson.GPIO itself, so I'll close this bug.

As you can see from the `ls` on the plugin-manager directory, only a single board has been detected. If the hardware and operating system are working correctly, two boards should be detected; one is the module and the other the baseboard. I'd suggest asking in the NVIDIA Jetson forum to determine why the ID file for the module is missing:

https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/70

Sorry this isn't more help.
